
<template>
    <div>
      <h1 class="cookie-policy-h1">Cookie Policy</h1>
      <p>
        Effective Date: 30-Aug-2023 <br />
        Last Updated: 30-Aug-2023
      </p>
  
      &nbsp;
      <h5>What are cookies?</h5>
      <div class="cookie-policy-p">
       <p>This Cookie Policy explains what cookies are and how we use them, the types of cookies we use i.e, the information we collect using cookies and how that information is used, and how to manage the cookie settings.</p> <p>Cookies are small text files that are used to store small pieces of information. They are stored on your device when the website is loaded on your browser. These cookies help us make the website function properly, make it more secure, provide better user experience, and understand how the website performs and to analyze what works and where it needs improvement.</p>
      </div>
  
      <!-- Other content -->
      &nbsp;
      <h5>How do we use cookies?</h5>
      <div class="cookie-policy-p">
        <p><!-- Your content --></p>
      </div>
  
      <!-- Other content -->
      &nbsp;
      <h5>Types of Cookies we use</h5>
      <div class="cky-audit-table-element"></div>
  
      <!-- Other content -->
      &nbsp;
      <h5 style="margin-bottom: 20px;">Manage cookie preferences</h5>
      <a class="cky-banner-element" @click="openCookieSettings">Cookie Settings</a> <br />
  
      <!-- Other content -->
  
      <div>
        <p><!-- Your content --></p>
        <p>
          <!-- Links to browser support documents -->
        </p>
      </div>
  
      <!-- Other content -->
  
      <p class="cookie-policy-p">
        Cookie Policy Generated By
        <a
          target="_blank"
          href="https://www.cookieyes.com/?utm_source=CP&utm_medium=footer&utm_campaign=UW"
        >
          CookieYes - Cookie Policy Generator
        </a>
        .
      </p>
    </div>
    <router-link to="/">Home</router-link>
  </template>
  
  <script>
  export default {
    name:'cookiePolicy',
    methods: {
      openCookieSettings() {
        // Implement the logic for opening cookie settings
      },
    },
  };
  </script>
  <style>
  .cky-banner-element {
    padding: 8px 30px;
    background: #f8f9fa;
    color: #858a8f;
    border: 1px solid #dee2e6;
    box-sizing: border-box;
    border-radius: 2px;
    cursor: pointer;
  }
  /* Add any other styles here */
</style>

  
